SETUP_TEXT = {
    "ru": {
        "subtitle": "Настройка магазина в Telegram",
        "intro": "Подключим FunPay и Telegram, затем настроим доступ. Ctrl+C — выйти без сохранения.",
        "step_funpay": "Аккаунт FunPay",
        "step_telegram": "Бот в Telegram",
        "step_password": "Доступ к панели",
        "step_connection": "Подключение FunPay",
        "golden_key": "Откройте funpay.com в своём браузере. В инструментах разработчика найдите Cookies → golden_key и скопируйте значение.",
        "golden_key_error": "Нужно 32 латинские буквы или цифры. Скопируйте только значение cookie.",
        "user_agent": "User-Agent браузера. Нажмите Enter, чтобы оставить стандартный.",
        "user_agent_error": "Введите одну строку латиницей, не длиннее 1024 символов.",
        "botfather": "Откройте https://t.me/BotFather и отправьте /newbot.\nНазвание: {name}\nUsername, например: {username}\nСкопируйте выданный токен. Он будет скрыт при вводе.",
        "token": "Токен от BotFather",
        "token_error": "Не удалось подключиться. Проверьте токен и доступ к Telegram.",
        "token_checking": "Проверяю токен через Telegram...",
        "token_unauthorized": "Telegram отклонил токен (401/404). Скопируйте действующий токен этого бота из @BotFather; отозванный токен не работает.",
        "token_timeout": "Telegram не ответил вовремя. Токен пока не проверен. Повторите проверку или настройте прокси.",
        "token_network_error": "Не удалось соединиться с api.telegram.org. Токен пока не проверен. Проверьте интернет, DNS, VPN или настройте прокси Telegram.",
        "token_proxy_error": "Не удалось подключиться через прокси. Проверьте адрес, порт, логин и пароль прокси либо выберите прямое подключение.",
        "token_tls_error": "Не удалось проверить TLS-сертификат Telegram. Проверьте дату и время компьютера, сертификаты и настройки прокси или антивируса.",
        "token_rate_limit": "Telegram ограничил частоту запросов (429). Подождите и повторите проверку этого токена.",
        "token_service_error": "Telegram временно недоступен (HTTP {status}). Повторите проверку позже; это не означает, что токен неверный.",
        "token_api_error": "Telegram отклонил проверку токена (код {status}). Проверьте подключение и повторите попытку.",
        "token_response_error": "Получен некорректный ответ вместо данных Telegram. Проверьте прокси и доступ к api.telegram.org.",
        "token_internal_error": "Внутренняя ошибка проверки токена: {error_type}. Это ошибка программы, а не подтверждение неверного токена. Сохраните этот тип ошибки для диагностики.",
        "token_format": "Токен должен содержать числовой ID, двоеточие и секретную часть.",
        "username_error": "Токен принят Telegram, но username не соответствует настройкам проекта: он должен начинаться с coxerhubfp_ и заканчиваться на bot.",
        "connected": "Подключён @{username}",
        "retry": "1  Ввести токен заново\n2  Настроить прокси Telegram и повторить\n3  Выйти\n4  Повторить проверку этого токена",
        "password": "Придумайте пароль панели: от 12 символов, заглавная и строчная буквы, цифра.",
        "password_error": "Нужно от 12 символов с буквами обоих регистров и цифрой; не более 72 байт.",
        "password_confirm": "Повторите пароль",
        "password_mismatch": "Пароли различаются. Попробуйте ещё раз.",
        "proxy": "Прокси для {service}. Enter — подключаться напрямую.\nФормат: scheme://login:password@ip:port",
        "proxy_error": "Прокси не отвечает или адрес неверен. Проверьте данные либо нажмите Enter для прямого подключения.",
        "hidden": "скрытый ввод",
        "choice_error": "Выберите один из указанных номеров.",
        "review": "Всё готово к сохранению",
        "review_body": "Язык: Русский\nFunPay: ключ добавлен\nTelegram: токен проверен\nПароль панели: задан\nРассылки и автообновление: отключены",
        "save": "1  Сохранить настройки\n2  Выйти без сохранения",
        "complete": "Настройки сохранены. Запустите бот, откройте его в Telegram и отправьте пароль панели. Затем используйте /menu.",
        "existing": "Настройки уже есть. Они сохранены без изменений. Можно запускать бот.",
        "cancelled": "Настройка отменена. Новая конфигурация не сохранена.",
        "secret_unavailable": "Скрытый ввод недоступен. Откройте обычный терминал и повторите запуск.",
        "failed": "Не удалось завершить настройку. Проверьте доступ к папке и повторите запуск. Секреты не выведены.",
        "proxy_done": "Подключение к @{username} настроено.",
        "environment": "Проверка системы",
        "python_error": "Нужен Python 3.11. Установите его с python.org и повторите запуск.",
        "platform_error": "Поддерживаются Windows, Linux и macOS.",
        "environment_error": "Окружение .venv повреждено или создано другой версией Python. Переименуйте эту папку и повторите настройку.",
        "venv": "Подготовка отдельного окружения .venv",
        "dependencies": "Установка зависимостей с проверкой хешей. При первом запуске потребуется интернет.",
        "install_error": "Установка не завершена. Проверьте интернет и доступ к папке. На Debian/Ubuntu также нужен пакет python3.11-venv. Повторный запуск продолжит подготовку.",
        "ready": "Окружение готово",
        "launch": "Запуск: {command}",
        "missing_environment": "Сначала запустите setup.py, чтобы подготовить окружение.",
        "check_ok": "Проверка Python и платформы пройдена. Файлы не изменены.",
        "preview": "Предпросмотр мастера. Данные не запрашиваются и не сохраняются.",
        "preview_events": "Примеры оформления статусов (запросы не отправляются):",
    },
    "en": {
        "subtitle": "Set up your store in Telegram",
        "intro": "Connect FunPay and Telegram, then secure your panel. Ctrl+C exits without saving.",
        "step_funpay": "FunPay account",
        "step_telegram": "Telegram bot",
        "step_password": "Panel access",
        "step_connection": "FunPay connection",
        "golden_key": "Open funpay.com in your browser. In developer tools, find Cookies → golden_key and copy its value.",
        "golden_key_error": "Use exactly 32 ASCII letters or digits. Copy only the cookie value.",
        "user_agent": "Browser User-Agent. Press Enter to use the default.",
        "user_agent_error": "Enter one ASCII line, up to 1024 characters.",
        "botfather": "Open https://t.me/BotFather and send /newbot.\nName: {name}\nUsername example: {username}\nCopy the token. Your input will be hidden.",
        "token": "Token from BotFather",
        "token_error": "Connection failed. Check your token and access to Telegram.",
        "token_checking": "Checking the token with Telegram...",
        "token_unauthorized": "Telegram rejected the token (401/404). Copy the current token for this bot from @BotFather; revoked tokens no longer work.",
        "token_timeout": "Telegram did not respond in time. The token has not been verified. Retry or configure a proxy.",
        "token_network_error": "Could not connect to api.telegram.org. The token has not been verified. Check your connection, DNS, VPN or configure a Telegram proxy.",
        "token_proxy_error": "Could not connect through the proxy. Check its address, port and credentials, or use a direct connection.",
        "token_tls_error": "Could not verify Telegram's TLS certificate. Check the computer's date and time, certificates, proxy or antivirus settings.",
        "token_rate_limit": "Telegram rate-limited the request (429). Wait before retrying this token.",
        "token_service_error": "Telegram is temporarily unavailable (HTTP {status}). Retry later; this does not mean the token is invalid.",
        "token_api_error": "Telegram rejected the token check (code {status}). Check your connection and retry.",
        "token_response_error": "Received an invalid response instead of Telegram data. Check your proxy and access to api.telegram.org.",
        "token_internal_error": "Internal token-check error: {error_type}. This is a program error, not proof of an invalid token. Keep this error type for diagnostics.",
        "token_format": "Use the numeric bot ID, a colon and the secret part of the token.",
        "username_error": "Telegram accepted the token, but the username does not meet this project's requirements: it must start with coxerhubfp_ and end with bot.",
        "connected": "Connected to @{username}",
        "retry": "1  Enter the token again\n2  Configure a Telegram proxy and retry\n3  Exit\n4  Retry this token",
        "password": "Choose a panel password: at least 12 characters, uppercase, lowercase and a number.",
        "password_error": "Use at least 12 characters with both letter cases and a number; up to 72 bytes.",
        "password_confirm": "Repeat the password",
        "password_mismatch": "Passwords do not match. Try again.",
        "proxy": "Proxy for {service}. Press Enter for a direct connection.\nFormat: scheme://login:password@ip:port",
        "proxy_error": "The proxy is unavailable or invalid. Check its address or press Enter for a direct connection.",
        "hidden": "hidden input",
        "choice_error": "Choose one of the listed numbers.",
        "review": "Ready to save",
        "review_body": "Language: English\nFunPay: key provided\nTelegram: token verified\nPanel password: set\nBroadcasts and automatic updates: disabled",
        "save": "1  Save settings\n2  Exit without saving",
        "complete": "Settings saved. Start the bot, open its Telegram chat and send your panel password. Then use /menu.",
        "existing": "Settings already exist and have been preserved. You can start the bot.",
        "cancelled": "Setup cancelled. No new configuration was saved.",
        "secret_unavailable": "Hidden input is unavailable. Open a regular terminal and run setup again.",
        "failed": "Setup could not finish. Check folder permissions and retry. No secrets were printed.",
        "proxy_done": "Connection to @{username} configured.",
        "environment": "System check",
        "python_error": "Python 3.11 is required. Install it from python.org and run setup again.",
        "platform_error": "Windows, Linux and macOS are supported.",
        "environment_error": "The .venv environment is damaged or uses another Python version. Rename that folder and run setup again.",
        "venv": "Preparing the isolated .venv environment",
        "dependencies": "Installing dependencies with hash verification. The first run requires internet access.",
        "install_error": "Installation failed. Check internet access and folder permissions. Debian/Ubuntu also need python3.11-venv. Run setup again to resume preparation.",
        "ready": "Environment ready",
        "launch": "Start: {command}",
        "missing_environment": "Run setup.py first to prepare the environment.",
        "check_ok": "Python and platform checks passed. No files changed.",
        "preview": "Wizard preview. No data is requested or saved.",
        "preview_events": "Status appearance examples (no requests are sent):",
    },
}
LANGUAGE_OPTIONS = "1  Русский\n2  English"
LANGUAGE_PROMPT = "Язык / Language"
LANGUAGE_CHOICES = {"1": "ru", "2": "en", "ru": "ru", "en": "en"}
LANGUAGE_ERROR = "Введите 1 или 2 / Enter 1 or 2"
