PUBLIC_COMMANDS = (
    ("start", "menu_start_command_description"),
    ("menu", "cmd_menu"),
    ("restart", "cmd_restart"),
)
LEGACY_COMMANDS = (
    ("send_profile", ("profile",)),
    ("act_change_cookie", ("change_cookie", "golden_key")),
    ("act_manual_delivery_test", ("test_lot",)),
    ("act_upload_image", ("upload_chat_img", "upload_offer_img")),
    ("act_upload_backup", ("upload_backup",)),
    ("act_ban", ("ban",)),
    ("act_unban", ("unban",)),
    ("send_ban_list", ("black_list",)),
    ("act_edit_watermark", ("watermark",)),
    ("send_logs", ("logs",)),
    ("del_logs", ("del_logs",)),
    ("about", ("about",)),
    ("check_updates", ("check_updates",)),
    ("update", ("update",)),
    ("get_backup", ("get_backup",)),
    ("create_backup", ("create_backup",)),
    ("send_system_info", ("sys",)),
    ("ask_power_off", ("power_off",)),
    ("send_announcements_kb", ("announcements",)),
)
