MAX_UPLOAD_BYTES = 20 * 1024 * 1024
MAX_FILENAME_BYTES = 240
PRIVATE_FILE_MODE = 0o600
EMPTY_FILENAMES = frozenset({"", ".", ".."})
FORBIDDEN_FILENAME_CHARACTERS = frozenset('/\\<>:"|?*')
MIN_PRINTABLE_CHARACTER = 32
