UPLOAD_CONSENT_PREFIX = "plugin_consent"
UPLOAD_CONSENT_STATE = "plugin_upload_consent"
UPLOAD_CONSENT_TOKEN_BYTES = 16
UPLOAD_CHOICE_YES = "yes"
UPLOAD_CHOICE_NO = "no"
UPLOAD_CHOICES = frozenset({UPLOAD_CHOICE_YES, UPLOAD_CHOICE_NO})
UPLOAD_CALLBACK_PARTS = 3
