UPDATE_TEXTS = {
    "ru": {
        "title": "🔄 <b>Обновления CXH FP</b>",
        "current": "Установлена версия {version}. Проверяем только подписанные релизы проекта.",
        "available": "🦊 Доступна версия {version}\n\nКод будет проверен и сохранена предыдущая версия. После установки бот перезапустится. Настройки, товары и плагины останутся на месте.",
        "check": "🔎 Проверить обновления",
        "install": "⬆️ Обновить и перезапустить",
        "checking": "Проверяю релизы…",
        "latest": "Новых подписанных релизов нет.",
        "failed": "Обновление не установлено. Проверьте подключение и журнал. Текущая версия продолжает работать.",
        "busy": "Проверка или установка уже выполняется.",
        "expired": "Эта кнопка устарела. Откройте обновления заново.",
        "progress": "📦 Загружаю и проверяю обновление…",
        "restart": "🔄 Обновление проверено. Устанавливаю и перезапускаю бот…",
        "done": "✅ CXH FP обновлён до версии {version}. Бот запущен, ваши данные сохранены.",
        "rollback": "↩️ Обновление не прошло проверку запуска. Восстановлена предыдущая версия {version}.",
        "disabled": "Обновления пока не настроены. Текущая версия работает как обычно.",
        "dependencies": "Для этого релиза изменились зависимости. Сначала запустите setup.py в папке бота. Автоматическая установка остановлена, данные сохранены.",
        "managed": "Эту установку нельзя обновить из Telegram. Запустите бот через main.py; в Docker или готовой сборке обновите приложение обычным способом. Данные сохранены.",
    },
    "en": {
        "title": "🔄 <b>CXH FP updates</b>",
        "current": "Installed version: {version}. Only signed project releases are accepted.",
        "available": "🦊 Version {version} is available\n\nThe previous code will be saved before installation. The bot will restart afterwards. Settings, stock and plugins are preserved.",
        "check": "🔎 Check for updates",
        "install": "⬆️ Update and restart",
        "checking": "Checking releases…",
        "latest": "No new signed release is available.",
        "failed": "Update was not installed. Check the connection and log. The current version remains active.",
        "busy": "An update operation is already running.",
        "expired": "This button expired. Open updates again.",
        "progress": "📦 Downloading and verifying the update…",
        "restart": "🔄 Update verified. Installing and restarting…",
        "done": "✅ CXH FP updated to {version}. The bot is running and your data is preserved.",
        "rollback": "↩️ The new version failed to start. Version {version} was restored.",
        "disabled": "Updates are not configured yet. The installed version remains active.",
        "dependencies": "This release changes dependencies. Run setup.py in the bot directory first. Automatic installation stopped; your data is preserved.",
        "managed": "This installation cannot update from Telegram. Start the bot through main.py; update Docker containers or packaged applications using their normal installation method. Your data is preserved.",
    },
}
